# arxivの学問領域の指定
subject: 'astro-ph'

# 検索キーワード
keywords:
        protoplanetary disk: 3
        protoplanetary disks: 3
        protoplanetary disc: 3
        protoplanetary discs: 3
        protostar: 3
        protostars: 3
        protostellar disk: 3
        protostellar disc: 3
        protostellar disks: 3
        protostellar discs: 3
        protostellar envelopes: 3
        protostellar: 2
        VeLLOs: 2
        star formation: 1
        planet formation: 1
        disk formation: 1
        circumstellar disk: 1
        circumstellar disks: 1
        spiral arm: 1
        spiral arms: 1
        streamer: 1
        streamers: 1
        cavity: 1
        cavities: 1
        outflow: 1
        machine learning: 1
        CNN: 1
        principal component analysis: 1
        PCA: 1

# 通知の閾値
score_threshold: 1
